name: publish
on:
  push:
    tags: [ 'v*' ]
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Configure Sonatype credentials
        run: |
          mkdir -p ~/.sbt/1.0
          cat > ~/.sbt/1.0/sonatype_credentials <<EOF
          realm=Sonatype Nexus Repository Manager
          host=central.sonatype.com
          user=$SONATYPE_USERNAME
          password=$SONATYPE_PASSWORD
          EOF
      - name: Import GPG key
        run: |
          echo "${{ secrets.PGP_SECRET }}" | base64 -d | gpg --batch --import
      - name: Publish Release JAR
        if: startsWith(github.ref,'refs/tags/v')
        run: |
          sbt \
            'set every publishTo := { val d = baseDirectory.value / "central-bundle"; Some("bundle" at s"file://${d.getAbsolutePath}") }' \
            +publishSigned
          PROJECT=$(basename "$GITHUB_REPOSITORY")
          VERSION=${GITHUB_REF_NAME##v}
          DATE_TIME=$(date +%Y%m%d-%H%M%S)
          ZIP_FILE="${PROJECT}-v${VERSION}-${DATE_TIME}.zip"
          (cd central-bundle && zip -rq ../"$ZIP_FILE" .)
          curl --fail-with-body -sS \
            -u "$SONATYPE_USERNAME:$SONATYPE_PASSWORD" \
            -F bundle=@"$ZIP_FILE" \
            -w "\nHTTP %{http_code}\n" \
            "https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC"
      - name: Publish Snapshot JAR
        if: github.ref == 'refs/heads/main'
        run: |
          sbt \
            'set every publishTo := Some("central-snapshots" at "https://central.sonatype.com/repository/maven-snapshots/")' \
            +publishSigned
