name: Scala Steward
on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        if: ${{ !github.event.repository.fork }}
        uses: tibdex/github-app-token@v1
        with:
          app_id: 111016
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: scala-steward-org/scala-steward-action@v2.36.0
        if: ${{ !github.event.repository.fork }}
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          author-email: "82752207+j5ik2o-bot[bot]@users.noreply.github.com"
          author-name: "j5ik2o-bot[bot]"
