name: Snapshot
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
jobs:
  snapshot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - uses: actions/checkout@v2.3.5
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
        fetch-depth: 0
    - uses: olafurpg/setup-scala@v13
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v6
    - uses: olafurpg/setup-gpg@v3
    - run: sbt -v ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
    - name: clean up
      run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
